### ISSUE TITLE
Pull request syntax to vim/vim

### ISSUE THREAD

**Issue by 89z** [PProvost/vim-ps1#50] opened 2021-03-30 23:58 UTC
Currently Vim does not have PowerShell syntax:

https://github.com/vim/vim/tree/f6bdd82c/runtime/syntax

I raised the issue with the Vim developers, and they say a maintainer from this repo needs to make a pull request on the Vim repo, before any change can be made.

Would the maintainers here be interested in doing that?

**Comment by heaths** [comment] 2021-03-31 00:21
Is there an issue you raised with them? What all should be included - everything in our repo (sans READMEs and what not)?

**Comment by 89z** [comment] 2021-03-31 00:24
I think just this would be fine:

https://github.com/PProvost/vim-ps1/blob/master/syntax/ps1.vim

**Comment by heaths** [comment] 2021-03-31 00:44
We have compilers and other files, which I see for other languages in vim. I don't see as much value in just our syntax file, as this bundle offers so much more.

**Comment by 89z** [comment] 2021-03-31 00:53
Correction, this is needed too:

https://github.com/PProvost/vim-ps1/blob/master/ftdetect/ps1.vim

**Comment by heaths** [comment] 2021-03-31 00:56
I opened an issue with vim. I'll see what all they want. AFAIC, it's all or nothing or I don't see the fully value in being in-box when this is easy to obtain as a bundle or other means in our README. This will also be the most up-to-date way of getting updates to this repo, but as long as bundle take precedent over in-box scripts nothing would preclude users from having both.

**Comment by 89z** [comment] 2021-03-31 01:14
I think there is value in having some common languages supported out of the box with Vim.

Sady thats not really the current state of things, as Vim include a whole bunch of crap languages no one ever heard of, but also some popular ones. I dont agree that all PowerShell should be included. For example I dont have any need for plugins or anything like that, just syntax. If it was up to me, I would do syntax only, or nothing. I guess we will see what happens.

**Comment by dkearns** [comment] 2021-03-31 09:21
> I opened an issue with vim. I'll see what all they want. AFAIC, it's all or nothing or I don't see the fully value in being in-box when this is easy to obtain as a bundle or other means in our README. This will also be the most up-to-date way of getting updates to this repo, but as long as bundle take precedent over in-box scripts nothing would preclude users from having both.

Yes, this is how it works with, for example, vim-ruby.  We send the files upstream if there's any major changes but generally just try to make sure the latest is included with every point release of Vim.

**Comment by Konfekt** [comment] 2021-04-01 07:20
>  I dont have any need for plugins or anything like that, just syntax.

What is a need? For example, indent and keyword lookup by pressing `K` make life simpler, as does syntax highlighting. No strong reasons to exclude the former but include the latter.

**Comment by heaths** [comment] 2021-04-02 07:52
Duplicate of vim/vim#8041

**Closed by heaths** 2021-04-02 07:52 UTC
